ppw_story4/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name="register"),
    path('', include('profilepage.urls')),
    path('', include('django.contrib.auth.urls')),
]

profilepage/urls.py
from django.urls import path
from . import views

app_name = 'profilepage'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('my-profile/', views.profile_page, name='profile_page'),
    path('my-games/', views.game_page, name='game_page'),
    path('my-accordion/', views.accordion_page, name='accordion_page'),
    path('my-booksearcher/', views.booksearcher_page, name='booksearcher_page'),
    path('my-booksearcher/<str:title>/', views.booksearcher_page_api, name='booksearcher_page_api'),
    path('my-welcome/', views.welcome_page, name='welcome_page'),
    path('my-courses/', views.course_display_view, name='course_display_view'),
    path('my-courses/<int:my_id>/', views.course_detail_view, name='course_detail_view'),
    path('my-courses/<int:my_id>/delete/', views.course_delete_view, name='course_delete_view'),
    path('my-courses/create/', views.course_create_view, name='course_create_view'),
    path('my-activities/activity-create/', views.activity_create_view, name='activity_create_view'),
    path('my-activities/activity-registration/', views.activity_registration_view, name='activity_registration_view'),
    path('my-activities/', views.activity_display_view, name='activity_display_view'),
]

profilepage/models.py
from django.db import models
from django.urls import reverse

NUMBERS = (('', 'Choose...'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), )
TERMS = (('', 'Choose...'), ('Odd Term 2020/2021', 'Odd Term 2020/2021'), ('Even Term 2019/2020', 'Even Term 2020/2021'), ('Odd Term 2019/2020', 'Odd Term 2019/2020'), )
GENDER = (('', 'Choose...'), ('Male', 'Male'), ('Female', 'Female'), ('Prefer not to answer', 'Prefer not to answer'), )

class Course(models.Model):
    title = models.CharField(max_length=160)
    term = models.CharField(max_length=160, choices=TERMS)
    lecturer = models.CharField(max_length=160)
    credits = models.CharField(max_length=1, choices=NUMBERS)
    place = models.CharField(max_length=99)
    description = models.CharField(max_length=500, default='')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"/my-courses/{self.id}/"

class Activity(models.Model):
    name = models.CharField(max_length=160)
    date = models.DateField()

    def __str__(self):
        return self.name

class Person(models.Model):
    full_name = models.CharField(max_length=160)
    gender = models.CharField(max_length=20, choices=GENDER)
    activity_registered = models.ForeignKey(Activity, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name

profilepage/forms.py
from django import forms
from .models import Course, Activity, Person
from django.forms import ModelForm, Textarea, TextInput

NUMBERS = (('', 'Choose...'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), )
TERMS = (('', 'Choose...'), ('Odd Term 2020/2021', 'Odd Term 2020/2021'), ('Even Term 2019/2020', 'Even Term 2020/2021'), ('Odd Term 2019/2020', 'Odd Term 2019/2020'), )
GENDER = (('', 'Choose...'), ('Male', 'Male'), ('Female', 'Female'), ('Prefer not to answer', 'Prefer not to answer'), )

class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = "__all__"
        widgets = {
            'title': TextInput(attrs={'placeholder': 'ex: Computer & Society', 'required': True}),
            'term': forms.Select(choices=TERMS, attrs={'class': 'form-control', 'required': True}),
            'lecturer': TextInput(attrs={'placeholder': 'ex: Laksmita Rahadianti', 'required': True}),
            'credits': forms.Select(choices=NUMBERS, attrs={'class': 'form-control', 'required': True}),
            'place': TextInput(attrs={'placeholder': 'ex: 2.2502', 'required': True}),
            'description': Textarea(attrs={'rows': 5, 'cols': 50, 'placeholder': 'ex: This course is awesome.', 'required': True}),
            }

class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = "__all__"
        widgets = {
            'name': TextInput(attrs={'placeholder': 'ex: Skirmish', 'required': True}),
            'date': TextInput(attrs={'placeholder': 'ex: 2000-10-20', 'required': True}),
        }

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = "__all__"
        widgets = {
            'full_name': TextInput(attrs={'placeholder': 'ex: Jonathan Joestar', 'required': True}),
            'gender': forms.Select(choices=GENDER, attrs={'class': 'form-control', 'required': True}),
        }

profilepage/views.py
from django.http import Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Course, Activity, Person
from .forms import CourseForm, ActivityForm, PersonForm
import urllib.request, json

def landing_page(request): # Story 9
    return render(request, "landing-page.html")

def welcome_page(request): # Story 9
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    return render(request, "welcome-page.html", {'visit_amount': num_visits})

def profile_page(request): # Story 4
    return render(request, "profile-page.html")

def game_page(request): # Story 4
    return render(request, "game-page.html")

def accordion_page(request): # Story 7
    return render(request, "accordion/accordion-page.html")

def booksearcher_page(request): # Story 8
    return render(request, "booksearcher/booksearcher-page.html")

def booksearcher_page_api(request, title): # Story 8
    link = urllib.parse.quote("https://www.googleapis.com/books/v1/volumes?q=" + title,"/:?=")
    with urllib.request.urlopen(link) as url:
        global data
        data = json.loads(url.read().decode())
    return JsonResponse(data)

def course_display_view(request): # Story 5
    queryset = Course.objects.all()
    return render(request, "course/course-display.html", {'object_list': queryset})

def course_create_view(request): # Story 5
    my_form = CourseForm(request.POST or None)
    if my_form.is_valid():
        Course.objects.create(**my_form.cleaned_data)
        return redirect('/my-courses/')
    return render(request, "course/course-create.html", {'form': my_form})

def course_detail_view(request, my_id): # Story 5
    obj = get_object_or_404(Course, id=my_id)
    return render(request, "course/course-detail.html", {'object': obj})

def course_delete_view(request, my_id): # Story 5
    obj = get_object_or_404(Course, id=my_id)
    if request.method == 'POST':
        obj.delete()
        return redirect('/my-courses/')
    return render(request, "course/course-delete.html", {'object': obj})

def activity_create_view(request): # Story 6
    this_form = ActivityForm(request.POST or None)
    if this_form.is_valid():
        Activity.objects.create(**this_form.cleaned_data)
        return redirect('/my-activities/')
    context = {
        'page_title': 'List an activity',
        'form': this_form
    }
    return render(request, "activity/activity-create.html", context)

def activity_registration_view(request): # Story 6
    the_form = PersonForm(request.POST or None)
    if the_form.is_valid():
        Person.objects.create(**the_form.cleaned_data)
        return redirect('/my-activities/')
    context = {
        'page_title': 'Register to an activity',
        'form': the_form
    }
    return render(request, "activity/activity-registration.html", context)

def activity_display_view(request): # Story 6
    person_entries = Person.objects.all()
    activity_entries = Activity.objects.all()
    context = {
        'page_title': 'Display activity',
        'person': person_entries,
        'activity': activity_entries
    }
    return render(request, "activity/activity-display.html", context)

profilepage/templates/activity/activity-create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-4">
    <form action='.' method='POST'> {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-lg-8 mb-0">
                {{ form.name|as_crispy_field }}
            </div>
            <div class="form-group col-lg-4 mb-0">
                {{ form.date|as_crispy_field }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'profilepage:activity_display_view' %}"><div class="btn btn-secondary">Back</div></a>
    </form>
</div>
{% endblock %}

profilepage/templates/activity/activity-display.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-lg-12 webTitle">
    <h2>My Activities</h2>
    <h3>The activities people registered are here.</h3>
</div>
<div class="container">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg-6" style="text-align: right; margin-bottom: 4em;"><a href="{% url 'profilepage:activity_create_view' %}"><div class="btn btn-primary">+ Add Activity</div></a></div>
            <div class="col-lg-6" style="text-align: left; margin-bottom: 4em;"><a href="{% url 'profilepage:activity_registration_view' %}"><div class="btn btn-primary">+ Register</div></a></div>
        </div>
        <div class="row">
            {% if activity %}
                {% for i in activity %}
                    <div class="card" style="width: 16rem; margin-right: 4rem;">
                        <div class="card bg-success text-white">
                            <img class="card-img-top" src="{% static 'img/people-avatar.png' %}" alt="Card image">
                            <div class="card-body" style="margin-left: 2rem; margin-right: 2rem;">
                                <h5 class="card-title">{{ i.name }}</h5>
                                <p class="card-text">Registered:</p>
                                <ul>
                                    {% for j in person %}
                                        {% if j.activity_registered.name == i.name %}
                                            <p class="card-text"><li>{{ j.full_name }}</li></p>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h5>There is no activity being held.</h5>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

profilepage/templates/activity/activity-registration.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-4">
    <form action='.' method='POST'> {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-lg-8 mb-0">
                {{ form.full_name|as_crispy_field }}
            </div>
            <div class="form-group col-lg-4 mb-0">
                {{ form.gender|as_crispy_field }}
            </div>
        </div>
        {{ form.activity_registered|as_crispy_field }}
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'profilepage:activity_display_view' %}"><div class="btn btn-secondary">Back</div></a>
    </form>
</div>
{% endblock %}