ppw_story4/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name="register"),
    path('', include('profilepage.urls')),
    path('', include('django.contrib.auth.urls')),
]

profilepage/urls.py
from django.urls import path
from . import views

app_name = 'profilepage'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('my-profile/', views.profile_page, name='profile_page'),
    path('my-games/', views.game_page, name='game_page'),
    path('my-accordion/', views.accordion_page, name='accordion_page'),
    path('my-booksearcher/', views.booksearcher_page, name='booksearcher_page'),
    path('my-booksearcher/<str:title>/', views.booksearcher_page_api, name='booksearcher_page_api'),
    path('my-welcome/', views.welcome_page, name='welcome_page'),
    path('my-courses/', views.course_display_view, name='course_display_view'),
    path('my-courses/<int:my_id>/', views.course_detail_view, name='course_detail_view'),
    path('my-courses/<int:my_id>/delete/', views.course_delete_view, name='course_delete_view'),
    path('my-courses/create/', views.course_create_view, name='course_create_view'),
    path('my-activities/activity-create/', views.activity_create_view, name='activity_create_view'),
    path('my-activities/activity-registration/', views.activity_registration_view, name='activity_registration_view'),
    path('my-activities/', views.activity_display_view, name='activity_display_view'),
]

profilepage/models.py
from django.db import models
from django.urls import reverse

NUMBERS = (('', 'Choose...'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), )
TERMS = (('', 'Choose...'), ('Odd Term 2020/2021', 'Odd Term 2020/2021'), ('Even Term 2019/2020', 'Even Term 2020/2021'), ('Odd Term 2019/2020', 'Odd Term 2019/2020'), )
GENDER = (('', 'Choose...'), ('Male', 'Male'), ('Female', 'Female'), ('Prefer not to answer', 'Prefer not to answer'), )

class Course(models.Model):
    title = models.CharField(max_length=160)
    term = models.CharField(max_length=160, choices=TERMS)
    lecturer = models.CharField(max_length=160)
    credits = models.CharField(max_length=1, choices=NUMBERS)
    place = models.CharField(max_length=99)
    description = models.CharField(max_length=500, default='')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"/my-courses/{self.id}/"

class Activity(models.Model):
    name = models.CharField(max_length=160)
    date = models.DateField()

    def __str__(self):
        return self.name

class Person(models.Model):
    full_name = models.CharField(max_length=160)
    gender = models.CharField(max_length=20, choices=GENDER)
    activity_registered = models.ForeignKey(Activity, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name

profilepage/forms.py
from django import forms
from .models import Course, Activity, Person
from django.forms import ModelForm, Textarea, TextInput

NUMBERS = (('', 'Choose...'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), )
TERMS = (('', 'Choose...'), ('Odd Term 2020/2021', 'Odd Term 2020/2021'), ('Even Term 2019/2020', 'Even Term 2020/2021'), ('Odd Term 2019/2020', 'Odd Term 2019/2020'), )
GENDER = (('', 'Choose...'), ('Male', 'Male'), ('Female', 'Female'), ('Prefer not to answer', 'Prefer not to answer'), )

class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = "__all__"
        widgets = {
            'title': TextInput(attrs={'placeholder': 'ex: Computer & Society', 'required': True}),
            'term': forms.Select(choices=TERMS, attrs={'class': 'form-control', 'required': True}),
            'lecturer': TextInput(attrs={'placeholder': 'ex: Laksmita Rahadianti', 'required': True}),
            'credits': forms.Select(choices=NUMBERS, attrs={'class': 'form-control', 'required': True}),
            'place': TextInput(attrs={'placeholder': 'ex: 2.2502', 'required': True}),
            'description': Textarea(attrs={'rows': 5, 'cols': 50, 'placeholder': 'ex: This course is awesome.', 'required': True}),
            }

class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = "__all__"
        widgets = {
            'name': TextInput(attrs={'placeholder': 'ex: Skirmish', 'required': True}),
            'date': TextInput(attrs={'placeholder': 'ex: 2000-10-20', 'required': True}),
        }

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = "__all__"
        widgets = {
            'full_name': TextInput(attrs={'placeholder': 'ex: Jonathan Joestar', 'required': True}),
            'gender': forms.Select(choices=GENDER, attrs={'class': 'form-control', 'required': True}),
        }

profilepage/views.py
from django.http import Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Course, Activity, Person
from .forms import CourseForm, ActivityForm, PersonForm
import urllib.request, json

def landing_page(request): # Story 9
    return render(request, "landing-page.html")

def welcome_page(request): # Story 9
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    return render(request, "welcome-page.html", {'visit_amount': num_visits})

def profile_page(request): # Story 4
    return render(request, "profile-page.html")

def game_page(request): # Story 4
    return render(request, "game-page.html")

def accordion_page(request): # Story 7
    return render(request, "accordion/accordion-page.html")

def booksearcher_page(request): # Story 8
    return render(request, "booksearcher/booksearcher-page.html")

def booksearcher_page_api(request, title): # Story 8
    link = urllib.parse.quote("https://www.googleapis.com/books/v1/volumes?q=" + title,"/:?=")
    with urllib.request.urlopen(link) as url:
        global data
        data = json.loads(url.read().decode())
    return JsonResponse(data)

def course_display_view(request): # Story 5
    queryset = Course.objects.all()
    return render(request, "course/course-display.html", {'object_list': queryset})

def course_create_view(request): # Story 5
    my_form = CourseForm(request.POST or None)
    if my_form.is_valid():
        Course.objects.create(**my_form.cleaned_data)
        return redirect('/my-courses/')
    return render(request, "course/course-create.html", {'form': my_form})

def course_detail_view(request, my_id): # Story 5
    obj = get_object_or_404(Course, id=my_id)
    return render(request, "course/course-detail.html", {'object': obj})

def course_delete_view(request, my_id): # Story 5
    obj = get_object_or_404(Course, id=my_id)
    if request.method == 'POST':
        obj.delete()
        return redirect('/my-courses/')
    return render(request, "course/course-delete.html", {'object': obj})

def activity_create_view(request): # Story 6
    this_form = ActivityForm(request.POST or None)
    if this_form.is_valid():
        Activity.objects.create(**this_form.cleaned_data)
        return redirect('/my-activities/')
    context = {
        'page_title': 'List an activity',
        'form': this_form
    }
    return render(request, "activity/activity-create.html", context)

def activity_registration_view(request): # Story 6
    the_form = PersonForm(request.POST or None)
    if the_form.is_valid():
        Person.objects.create(**the_form.cleaned_data)
        return redirect('/my-activities/')
    context = {
        'page_title': 'Register to an activity',
        'form': the_form
    }
    return render(request, "activity/activity-registration.html", context)

def activity_display_view(request): # Story 6
    person_entries = Person.objects.all()
    activity_entries = Activity.objects.all()
    context = {
        'page_title': 'Display activity',
        'person': person_entries,
        'activity': activity_entries
    }
    return render(request, "activity/activity-display.html", context)

profilepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Raihan's Web: About him, his projects, his blogs, and his nowaday games.">
        <meta name="keyword" content="Raihan's Web">
        <meta name="author" content="Raihan Rizqi">
        <title>Raihan's Web</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="icon" href="{% static 'img/letter-r.png' %}" type="image/x-icon">
        {% block head %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark sticky-top">
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'profilepage:profile_page' %}">Raihan's Web</a>
            {% else %}
                <a class="navbar-brand" href="{% url 'profilepage:landing_page' %}">Raihan's Web</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">PROJECTS</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="https://www.figma.com/proto/nZa4tZb0xvH1vfDd3QBMnG/Pacil-Student-Pack-PSP?node-id=115%3A17&viewport=139%2C198%2C0.35254237055778503&scaling=scale-down" target="_blank">Pacil Student Pack prototype</a>
                                <a class="dropdown-item" href="https://story-raihan-mk1.herokuapp.com/" target="_blank">Story 1 PPW (Simple Web about My Profile)</a>
                                <a class="dropdown-item" href="https://www.figma.com/file/XEQVUXyuNYdFh4CtOTYddI/Prototype-Story-2?node-id=1%3A2" target="_blank">Story 2 PPW (HiFi Prototype)</a>
                                <a class="dropdown-item" href="{% url 'profilepage:profile_page' %}">Story 3 PPW (HTML Bootstrap)</a>
                                <a class="dropdown-item" href="{% url 'profilepage:profile_page' %}">Story 4 PPW (Django Views + Template)</a>
                                <a class="dropdown-item" href="{% url 'profilepage:course_display_view' %}">Story 5 PPW (Django Models)</a>
                                <a class="dropdown-item" href="{% url 'profilepage:activity_display_view' %}">Story 6 PPW (Django Unit Tests)</a>
                                <a class="dropdown-item" href="{% url 'profilepage:accordion_page' %}">Story 7 PPW (JScript & JQuery)</a>
                                <a class="dropdown-item" href="{% url 'profilepage:booksearcher_page' %}">Story 8 PPW (AJAX Dynamic Data Access)</a>
                                <a class="dropdown-item" href="{% url 'profilepage:welcome_page' %}">Story 9 PPW (Auth, Session, and Cookies)</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">BLOGS</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="https://medium.com/@raihan66660" target="_blank">Medium</a>
                                <a class="dropdown-item" href="https://inilahblognyaraihan.blogspot.com/" target="_blank">Blogspot</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profilepage:game_page' %}">CURRENT GAMES</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Hello, {{ user.get_username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">LOGOUT</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">REGISTER</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">LOGIN</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>
        {% block body %}{% endblock %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <footer class="page-footer font-small">
            <div class="footer-copyright text-center py-2">© Raihan Rizqi Muhtadiin 2020</div>
        </footer>
    </body>
</html>

profilepage/templates/game-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-lg-12 webTitle">
    <h2>Current Games</h2>
    <h3>I'm currently playing these games.<br>Let's chitchat about 'em!</h3>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <img src="{% static 'img/fe-echoes.jpg' %}" alt="FE Echoes Cover Art" class="mx-auto img-fluid" style="width: 640px; height: 360px; object-fit: cover;">
            <h3 style="font-size: 24px; margin-top: 2em; margin-bottom: 1em; text-align: center;">Fire Emblem Echoes: Shadows of Valentia</h3>
            <p style="text-align: center; margin-bottom: 2em;">So far, this game is the 3rd Fire Emblem mainline title I've played. The former two being Fire Emblem Awakening and Fire Emblem Fates. My progress now is I'm about to enter the Thabes Labyrinth for the ultimate challenge.</p>
        </div>
        <div class="col-lg-6">
            <img src="{% static 'img/ff6-cover.jpg' %}" alt="FF6 Cover Art" class="mx-auto img-fluid" style="width: 640px; height: 360px; object-fit: cover;">
            <h3 style="font-size: 24px; margin-top: 2em; margin-bottom: 1em; text-align: center;">Final Fantasy 6</h3>
            <p style="text-align: center; margin-bottom: 2em;">So far, this game is the 5th Final Fantasy mainline title I've played. The other four are 13, 9, 8, and 7 (I've completed their main story bar 7). I also have completed the main story of 13-2 and got around 70% completion of main story for Lightning Returns.</p>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <img src="{% static 'img/p3p.jpg' %}" alt="Persona 3 Portable Cover" class="mx-auto img-fluid" style="width: 640px; height: 360px; object-fit: cover;">
            <h3 style="font-size: 24px; margin-top: 2em; margin-bottom: 1em; text-align: center;">Shin Megami Tensei: Persona 3 Portable</h3>
            <p style="text-align: center; margin-bottom: 2em;">A spin-off from its original titles, Shin Megami Tensei, I started playing this game because at the moment I just installed PPSSPP and don't know what game should I play first, so... yeah. The game has very dark story anyway.</p>
        </div>
        <div class="col-lg-6">
            <img src="{% static 'img/valkyria-chronicles.jpg' %}" alt="Valkyria Chronicles Cover Art" class="mx-auto img-fluid" style="width: 640px; height: 360px; object-fit: cover;">
            <h3 style="font-size: 24px; margin-top: 2em; margin-bottom: 1em; text-align: center;">Valkyria Chronicles</h3>
            <p style="text-align: center; margin-bottom: 2em;">One of the best strategy role-playing games until today, I've played the game until Chapter 3. So far, the story revolves around this boy Welkin and this girl I-don't-really-understand-who Alicia saving the city of Bruhl from invasion.</p>
        </div>
    </div>
</div>
{% endblock %}

profilepage/templates/landing-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top: 8%;">
    <div class="col-lg-12 text-center">
        <h3>Welcome to Raihan's Web.</h3>
    </div>
    <div class="col-lg-12 text-center" style="margin-top: 5%;">
        <p>You're not logged in.</p>
        <p>Login <a href="{% url 'login' %}">here</a></p>
    </div>
</div>
{% endblock %}

profilepage/templates/profile-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-lg-12 webTitle">
    <h2>Hello!</h2>
    <h3>Allow me to introduce myself.</h3>
</div>
<div class="container" style="margin-top: 4em; margin-bottom: 4em;">
    <div class="row">
        <div class="col-lg-4">
            <img src="{% static 'img/Raihan.png' %}" alt="Foto diri Raihan" class="mx-auto d-block img-fluid fotoDiri">
        </div>
        <div class="col-lg-8" style="padding-left: 2em;">
            <div class="dataField mx-auto d-block">Name: Raihan Rizqi Muhtadiin</div>
            <div class="dataField mx-auto d-block">Student ID: 1906353776</div>
            <div class="dataField mx-auto d-block">Batch: Maung 2019</div>
            <div class="dataField mx-auto d-block">Hobby: Play Fire Emblem and Final Fantasy, especially mainline series</div>
            <div class="dataField mx-auto d-block">University: Universitas Indonesia</div>
            <div class="dataField mx-auto d-block">Description:<br><div class="desc">Currently I am at my 3rd semester as an undergraduate student from Faculty of Computer Science at Universitas Indonesia. I am taking Information System major in search for more knowledge and experience about computer science combined with business and management. I have interest in game development and UI/UX Design. Outside computer industry, I am studying music composing, especially the orchestral one.</div></div>
        </div>
    </div>
</div>
<div class="container mt-4 mb-4" style="padding-left: 2em;">
    <div class="row">
        <div class="col-lg-6">
            <div class="titlePart">Educational History</div>
            <ul class="timeline1" style="margin-left: 2em;">
                <li>
                    <p>Universitas Indonesia</p>
                    <p>Depok, West Java, Indonesia</p>
                    <p>2019 - now</p>
                </li>
                <li>
                    <p>SMAIT Daarul Hikmah Boarding School</p>
                    <p>Bontang, East Borneo, Indonesia</p>
                    <p>2016 - 2019</p>
                </li>
                <li>
                    <p>SMPIT Daarul Hikmah Boarding School</p>
                    <p>Bontang, East Borneo, Indonesia</p>
                    <p>2013 - 2016</p>
                </li>
                <li>
                    <p>SDIT Asy Syaamil</p>
                    <p>Bontang, East Borneo, Indonesia</p>
                    <p>2007 - 2013</p>
                </li>
            </ul>
        </div>
        <div class="col-lg-6">
            <div class="titlePart">Accomplishments</div>
            <ul class="timeline2" style="margin-left: 2em;">
                <li>
                    <p>Awardee of Beasiswa Kaltimtuntas</p>
                    <p>East Borneo's Government tuition fee grant</p>
                    <p>Issued Jan 2020</p>
                </li>
                <li>
                    <p>2nd Winner of Lomba Karya Tulis Ilmiah</a>
                    <p>OSAGI VII Universitas Mulawarman Samarinda</p>
                    <p>Issued Feb 2017</p>
                </li>
                <li>
                    <p>3rd Best Speaker of English Debate Society</p>
                    <p>English Exhibition Days Universitas Trunajaya Bontang</p>
                    <p>Issued Oct 2016</p>
                </li>
                <li>
                    <p>3rd Winner of Final Kuis Kihajar Nasional</p>
                    <p>Kuis Kihajar Nasional Kemendikbud</p>
                    <p>Issued Nov 2015</p>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="container mt-4 mb-4" style="padding-left: 2em; text-align: center;">
    <div class="row">
        <div class="col-lg-6">
            <div class="titlePart">Skills</div>
            <ul class="timeline3 row">
                <div class="image-java col-lg-3">
                    <img src="{% static 'img/java.png' %}" alt="Java Logo" class="img-fluid logo">
                </div>
                <div class="java col-lg-9">
                    <li style="margin-bottom: 4em;">
                        <p>Java</p>
                        <p>Basic programming with Java</p>
                        <p>Learning since Jan 2020</p>
                    </li>
                </div>
                <div class="image-html-5 col-lg-3">
                    <img src="{% static 'img/html-5.png' %}" alt="Html5 Logo" class="img-fluid logo">
                </div>
                <div class="html5 col-lg-9">
                    <li style="margin-bottom: 4em;">
                        <p>HTML</p>
                        <p>Basic static web design with HTML</p>
                        <p>Learning since Nov 2019</p>
                    </li>
                </div>
                <div class="image-css col-lg-3">
                    <img src="{% static 'img/css.png' %}" alt="CSS Logo" class="img-fluid logo">
                </div>
                <div class="css col-lg-9">
                        <li style="margin-bottom: 4em;">
                        <p>CSS</p>
                        <p>Basic web design with CSS</p>
                        <p>Learning since Nov 2019</p>
                    </li>
                </div>
            </ul>
        </div>
        <div class="col-lg-6">
            <div class="titlePart">Experience</div>
            <ul class="timeline3 row">
                <div class="image-makara col-lg-3">
                    <img src="{% static 'img/makara.png' %}" alt="Makara Fasilkom UI" class="img-fluid logo">
                </div>
                <div class="makara col-lg-9">
                    <li style="margin-bottom: 4em;">
                        <p>Faculty of Computer Science, Universitas Indonesia</p>
                        <p>Teaching Assistant of Discrete Mathematics 1</p>
                        <p>Aug 2020 - now</p>
                    </li>
                </div>
                <div class="image-compfest col-lg-3">
                    <img src="{% static 'img/compfest.png' %}" alt="Compfest Logo" class="img-fluid logo">
                </div>
                <div class="compfest col-lg-9">
                    <li style="margin-bottom: 4em;">
                        <p>COMPFEST 12</p>
                        <p>Staff of Editorial Marketing</p>
                        <p>Feb 2020 - now</p>
                    </li>
                </div>
                <div class="image-dpm col-lg-3">
                    <img src="{% static 'img/dpmfasilkom.png' %}" alt="DPM Fasilkom Logo" class="img-fluid logo">
                </div>
                <div class="dpm col-lg-9">
                    <li style="margin-bottom: 4em;">
                        <p>DPM Fasilkom UI</p>
                        <p>Vice Head of Succession and Fostering Commission</p>
                        <p>Jan 2020 - now</p>
                    </li>
                </div>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <div class="connect" style="text-align: center; font-size: 30px;">
        Stay connected with me at:
    </div>
    <div class="socmed">
        <a href="https://www.instagram.com/raihanr2m"><img src="{% static 'img/instagram.png' %}" alt="Instagram" style="width: 3em; height: 3em;"></a>
        <a href="https://line.me/ti/p/~raihansurvival"><img src="{% static 'img/line.png' %}" alt="Line" style="width: 3em; height: 3em;"></a>
        <a href="https://twitter.com/RMuhtadiin"><img src="{% static 'img/twitter.png' %}" alt="Twitter" style="width: 3em; height: 3em;"></a>
        <a href="https://www.linkedin.com/in/raihan-rizqi-muhtadiin/"><img src="{% static 'img/linkedin.png' %}" alt="Linkedin" style="width: 3em; height: 3em;"></a>
        <a href="mailto: raihan66660@gmail.com"><img src="{% static 'img/gmail.png' %}" alt="Gmail" style="width: 3em; height: 3em;"></a>
        <a href="https://gitlab.com/Raiiz"><img src="{% static 'img/gitlab.png' %}" alt="Gitlab" style="width: 3em; height: 3em;"></a>
    </div>
</div>
{% endblock %}

profilepage/templates/welcome-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top: 8%;">
    <div class="col-lg-12 text-center">
        <h3>Welcome, {{ user.username }}</h3>
    </div>
    <div class="col-lg-12 text-center" style="margin-top: 5%;">
        <p>You have visited this page {{ visit_amount }} time{% if visit_amount > 1 %}s{% endif %}.</p>
    </div>
</div>
{% endblock %}